version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: webservice
      MYSQL_ROOT_PASSWORD: 8&pqA24iyQ01
      MYSQL_ROOT_HOST: '%'
    ports:
      - "13306:3306"
