spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    org:
      springframework:
        test:
          context:
            jdbc:
              SqlScriptsTestExecutionListener:
                DEBUG